### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by drcode2** [bargees/barge-pkg#22]
I can't install docker-compose

find: '/build/buildroot/output/target/usr/lib/python3.7/config-3.7m/': No such file or directory
>>> docker-compose 1.20.1 Downloading
>>> docker-compose 1.20.1 Extracting
>>> docker-compose 1.20.1 Patching
>>> docker-compose 1.20.1 Configuring
>>> docker-compose 1.20.1 Building
/bin/bash: /build/buildroot/output/host/bin/python: No such file or directory
make: *** [/build/buildroot/output/build/docker-compose-1.20.1/.stamp_built] Error 127
package/pkg-generic.mk:238: recipe for target '/build/buildroot/output/build/docker-compose-1.20.1/.stamp_built' failed

any idea?

**Comment by ailispaw** [comment]
Hi @drcode2 , thank you so much for using Barge and inquiring the question.

According to the docker-compose configuration file for Buildoot which barge-pkg uses,
https://github.com/buildroot/buildroot/blob/master/package/docker-compose/Config.in,
it needs a lot of python components to build it with -e options for barge-pkg.

Meanwhile, I would like to recommend you to follow the official installation of docker-compose instead of buildroot (barge-pkg) in this case.
https://docs.docker.com/compose/install/

```
$ sudo mkdir -p /opt/bin
$ sudo wget "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -O /opt/bin/docker-compose
$ sudo chmod +x /opt/bin/docker-compose
```

**Comment by drcode2** [comment]
It's working
Thank You
